[package]
name = "workshop"
version = "0.1.0"
edition = "2023_01"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.8.0"

[dev-dependencies]
cairo_test = "2.8.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"
